export enum Stage {
  NOTSTARTED = 'NOTSTARTED',

  STARTED = 'STARTED',

  ONGOING = 'ONGOING',

  COMPLETED = 'COMPLETED',

  SELECTED = 'SELECTED',

  REJECTEDBYME = 'REJECTEDBYME',

  NOOFFERRECEIVED = 'NOOFFERRECEIVED',

  NOTSELECTED = 'NOTSELECTED',
}
